baseURL = 'https://www.lewisbowman.com/'
languageCode = 'en-us'
title = 'LewisBowman'
theme = 'PaperMod'

SectionPagesMenu = "main"

[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = false